Update master Fri Nov 16 21:53:26 UTC 2018

diff --git a/stable/ibm-transadv-dev/templates/oidc-registration-script.yaml b/stable/ibm-transadv-dev/templates/oidc-registration-script.yaml
--- a/stable/ibm-transadv-dev/templates/oidc-registration-script.yaml
+++ b/stable/ibm-transadv-dev/templates/oidc-registration-script.yaml
@@ -14,10 +14,9 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  name: {{ template "fullname" . }}-{{ .Chart.Version | replace "." "" }}-odic-registration-script
-  namespace: "services"
+  name: {{ template "fullname" . }}-{{ .Chart.Version | replace "." "" }}-oidc-registration-script
   labels:
-    app: {{ template "fullname" . }}-{{ .Chart.Version | replace "." "" }}-odic-registration
+    app: {{ template "fullname" . }}-{{ .Chart.Version | replace "." "" }}-oidc-registration
     chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
     release: {{ .Release.Name }}
     heritage: {{ .Release.Service }}
@@ -30,14 +29,15 @@ data:
     user_input_client_id={{ .Values.authentication.oidc.clientId }}
     user_input_client_secret={{ .Values.authentication.oidc.clientSecret }}
 
-    if [ -z "${user_input_icp_auth_endpoint_port// }" ] || [ -z "${user_input_oidc_auth_endpoint_port// }" ] || [ -z "${user_input_client_id// }" ] || [ -z "${user_input_client_secret// }" ]
-    then
-      # at least one empty
-      echo "At least one required value is empty. OIDC will not be registered."
-      exit 0
-    fi
+    auto_icp_proxy_ip=""
+    auto_wlp_client_registration_secret=""
+
+    icp_proxy_ip=$1
+    wlp_client_registration_secret=$2
 
     enable_auth={{ .Values.ingress.enabled }}
+    namespace={{ .Release.Namespace }}
+    service_acount={{ .Values.security.serviceAccountName }}
 
     if [ $enable_auth = "false" ]
     then
@@ -46,21 +46,71 @@ data:
       exit 0
     fi
 
+    if [[ $namespace != "default" || $service_acount != "default" ]] && [[ -z "${icp_proxy_ip// }" || -z "${wlp_client_registration_secret// }" ]]
+    then
+      # Authentication needs to be enabled by an Admin
+      echo "Authentication needs to be enabled by an Admin after installation."
+      exit 0
+    fi
+
+    if [ -z "${user_input_icp_auth_endpoint_port// }" ] || [ -z "${user_input_oidc_auth_endpoint_port// }" ] || [ -z "${user_input_client_id// }" ] || [ -z "${user_input_client_secret// }" ]
+    then
+      # at least one empty
+      echo "At least one required value is empty. OIDC will not be registered: ICP master node endpoint, OIDC endpoint, client id or secret cannot be retrieved from helm chart."
+      exit 1
+    fi
+
+    # if icp_proxy_ip is non-empty
+    if [ -n "${icp_proxy_ip}" ]
+    then
+      auto_icp_proxy_ip=$icp_proxy_ip
+      echo "set icp proxy ip to" $auto_icp_proxy_ip
+    else
+      # this works on ICP: 2.1.0.3, 3.1.0 and 3.1.1 default namespace
+      auto_icp_proxy_ip=`kubectl get cm oauth-client-map -n services -o yaml | grep PROXY_IP | grep -v '"PROXY_IP"' | awk '{print $2}'`
+    fi
+
+    # if wlp_client_registration_secret is non-empty
+    if [ -n "${wlp_client_registration_secret}" ]
+    then
+      auto_wlp_client_registration_secret=`base64 --decode <<< $wlp_client_registration_secret`
+      echo "set Oauth client registration secret to *"
+    else
+      # this works on ICP: 2.1.0.3, 3.1.0 and 3.1.1 default namespace
+      auto_wlp_client_registration_secret="$(base64 --decode <<< `kubectl get secret platform-oidc-credentials -o yaml -n kube-system | grep OAUTH2_CLIENT_REGISTRATION_SECRET: | awk '{print $2}'`)"
+    fi
+
+    if [ -z "${auto_icp_proxy_ip// }" ]
+    then
+      echo "OIDC will not be registered: Proxy ip cannot is not set."
+      exit 1
+    fi
+
+    if [ -z "${auto_wlp_client_registration_secret// }" ]
+    then
+      echo "OIDC will not be registered: Oauth client registration secret is not set."
+      exit 1
+    fi
+
     # /jsons in ICP 2.1.0.3 is read only mount volumn
     mkdir -p /opt/oidc
     cp /jsons/oidc-registration.json /opt/oidc/oidc-registration.json
 
-    sed -i 's/___ICP_PROXY_IP___/'${ICP_PROXY_IP}'/g' /opt/oidc/oidc-registration.json
-    sed -i 's/___ICP_MASTER_IP___/'${ICP_MASTER_IP}'/g' /opt/oidc/oidc-registration.json
+    sed -i 's/___ICP_PROXY_IP___/'${auto_icp_proxy_ip}'/g' /opt/oidc/oidc-registration.json
+    sed -i 's/___ICP_MASTER_IP___/{{ .Values.authentication.icp.edgeIp }}/g' /opt/oidc/oidc-registration.json
 
     HTTP_CODE=""
     while true
     do
-      HTTP_CODE=`curl -k -o /dev/null -I  -w "%{http_code}" -X GET -u oauthadmin:$WLP_CLIENT_REGISTRATION_SECRET \
+      HTTP_CODE=`curl -k -o /dev/null -I  -w "%{http_code}" -X GET -u oauthadmin:$auto_wlp_client_registration_secret \
        -H "Content-Type: application/json" \
-       https://$ICP_MASTER_IP:{{ .Values.authentication.oidc.endpointPort }}/oidc/endpoint/OP/registration/{{ .Values.authentication.oidc.clientId }}`
+       https://{{ .Values.authentication.icp.edgeIp }}:{{ .Values.authentication.oidc.endpointPort }}/oidc/endpoint/OP/registration/{{ .Values.authentication.oidc.clientId }}`
       if [ $HTTP_CODE = "404" -o $HTTP_CODE = "200" ] ; then
          break;
+      fi
+      if [ $HTTP_CODE = "401" ]; then
+        echo "You must need an admin OIDC client registration secret."
+        exit 0
       fi
       sleep 2s
     done
@@ -69,10 +119,10 @@ data:
     then
       echo "Creating new client registration."
 
-      until curl -i -k -X POST -u oauthadmin:$WLP_CLIENT_REGISTRATION_SECRET \
+      until curl -i -k -X POST -u oauthadmin:$auto_wlp_client_registration_secret \
        -H "Content-Type: application/json" \
        --data @/opt/oidc/oidc-registration.json \
-       https://$ICP_MASTER_IP:{{ .Values.authentication.oidc.endpointPort }}/oidc/endpoint/OP/registration | grep '201 Created'; do sleep 1; done;
+       https://{{ .Values.authentication.icp.edgeIp }}:{{ .Values.authentication.oidc.endpointPort }}/oidc/endpoint/OP/registration | grep '201 Created'; do sleep 1; done;
 
       echo "Client is registered."
     else
@@ -81,10 +131,10 @@ data:
       max_retry=20
       while [ $retry -le $max_retry ]
       do
-        HTTP_CODE=`curl -k -o /dev/null -w "%{http_code}" -X PUT -u oauthadmin:$WLP_CLIENT_REGISTRATION_SECRET \
+        HTTP_CODE=`curl -k -o /dev/null -w "%{http_code}" -X PUT -u oauthadmin:$auto_wlp_client_registration_secret \
          -H "Content-Type: application/json" \
          --data @/opt/oidc/oidc-registration.json \
-         https://$ICP_MASTER_IP:{{ .Values.authentication.oidc.endpointPort }}/oidc/endpoint/OP/registration/{{ .Values.authentication.oidc.clientId }}`
+         https://{{ .Values.authentication.icp.edgeIp }}:{{ .Values.authentication.oidc.endpointPort }}/oidc/endpoint/OP/registration/{{ .Values.authentication.oidc.clientId }}`
         if [ $HTTP_CODE = "200" ]
         then
           echo "Replaced the client registration."
